CREATE DATABASE JUDGELIGHT;

# Defile user table
CREATE TABLE JUDGELIGHT.USER(
    STUDENT_ID varchar(5) NOT NULL,
    PASSWORD varchar(10) NOT NULL,
    PRIMARY KEY (ID),
);

# Defile result table
CREATE TABLE JUDGELIGHT.RESULT(
    STUDENT_ID varchar(5) NOT NULL,
    RESULT JSON NOT NULL,
    FOREIGN KEY (STUDENT_ID) REFERENCES USER(STUDENT_ID),
);

# Define problem table
CREATE TABLE JUDGELIGHT.PROBLEM{
    PROBLEM_ID varchar(5) NOT NULL,
    PROBLEM varchar(1000) NOT NULL,
    TEST_CASE JSON NOT NULL,
    SECRET_CASE JSON NOT NULL,
    PRIMARY KEY (PROBLEM_ID),
};
