CREATE DATABASE JUDGELIGHT;

CREATE TABLE JUDGELIGHT.USER (
    STUDENT_ID VARCHAR(5) NOT NULL PRIMARY KEY,
    STUDENT_PASSWORD VARCHAR(10) NOT NULL
);

CREATE TABLE JUDGELIGHT.RESULT (
    STUDENT_ID VARCHAR(5) NOT NULL PRIMARY KEY,
    RESULT JSON NOT NULL,
    FOREIGN KEY (STUDENT_ID) REFERENCES JUDGELIGHT.USER(STUDENT_ID)
);

CREATE TABLE JUDGELIGHT.PROBLEM (
    PROBLEM_ID VARCHAR(5) NOT NULL PRIMARY KEY,
    PROBLEM VARCHAR(1000) NOT NULL,
    TEST_CASE JSON NOT NULL,
    SECRET_CASE JSON NOT NULL
);

